### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jkakavas** [jkakavas/parse-issue-comment-action#1]
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango

**Comment by jkakavas** [comment]
@prodsecmachine create statement

```yaml
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
```

**Comment by jkakavas** [comment]
@prodsecmachine create statement

```yaml
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
```

**Comment by jkakavas** [comment]
@prodsecmachine create statement

```yaml
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
```

**Comment by jkakavas** [comment]
@prodsecmachine create statement

```yaml
---
# A list of tasty fruits
- Apple
- Orange
- Strawberry
- Mango
```

**Comment by jkakavas** [comment]
@prodsecmachine create statement

```yaml
status: "false update"
statement: "This is a test statement that would be added by a team"
product: kibana
cve_id: CVE-2021-1234
package: minimist
```

**Comment by jkakavas** [comment]
@prodsecmachine create statement

```yaml
status: "false update"
statement: "This is a test statement that would be added by a team"
product: kibana
cve_id: CVE-2021-1234
package: minimist
```

**Comment by jkakavas** [comment]
@prodsecmachine create statement

```yaml
status: "false update"
statement: "This is a test statement that would be added by a team"
product: kibana
cve_id: CVE-2021-1234
package: minimist
```

**Comment by jkakavas** [comment]
@prodsecmachine create statement

```yaml
status: "false update"
statement: "This is a test statement that would be added by a team"
product: kibana
cve_id: CVE-2021-1234
package: minimist
```
